### ISSUE TITLE
PreFer baseline prediction using LISS 

### ISSUE THREAD

**Issue by tanzir5** [odissei-lifecourse/life-sequencing-dutch#10]
I am creating two baselines: 

1. A baseline based on just age and sex:
         A logistic regression predicts "0" always and achieves accuracy of 0.78 and terrible f1 (0)
         A random forest predicts both 0 and 1, achieves accuracy of 0.79 and not so terrible f1. 
2. A Gradient Boosted Random Forest (GBRF) that takes into account all data from train.csv and train_background.csv

Model 2 is in progress right now with details in the comments.

**Comment by tanzir5** [comment]
PreFer submission procedure does not let me use train_outcome and entire train set for encoding holdout_train set. This makes target_encoding impossible. Sent an email to the organizers. 

TODO: attend office hour on May 6 if needed.

**Comment by tanzir5** [comment]
The phase2 submissions were done on May 13. I did the following changes: 

i) I used the variable 'cf20m130' as PROXY_TARGET for doing target_encoding since we do not have access to train_outcome during testing. cf20m130 is the question "Within how many years do you want to have a kid?"

ii) I uploaded a file containing the mean values of all the required variables in the training set since we cannot upload the train data but we can upload summary statistics. I use it to fill up the nan values. Point to be noted is that this contains variables that are created after the preprocessing involving one-hot-encoding and target-encoding, not the original variables. 

iii) I ran 10 different models each containing 10% of the preprocessed variables. I use a weighted scheme involving both the importance of a variable according to the GBRF and the f1 score of the associated GBRF to rank original un-processed variables. Then I take the top 200 strongest variables and ignore all other variables from the raw dataset. I created the GBRF and submitted in phase 2.

**Comment by f-hafner** [comment]
we're not working on this anymore, closing
