### ISSUE TITLE
Preparing longer sequences with household data

### ISSUE THREAD

**Issue by f-hafner** [odissei-lifecourse/life-sequencing-dutch#101]
I had a look at `pop2vec.llm.src.new_code.preprocess_data.process_and_write`

#### Questions I had
- where are the events ordered?
- how do we integrate it with the other data?
- do we *need* to create yearly files (as Lucas writes in the email)? do we want start and end dates? 

#### Observations
- `Age` column missing -> we will need background data by year x rinpersoon
- there are some columns with NA, such as `yearBirthOldestChild`, but I think the code deals with this already
- I assume the ordering happens in `create_life_seq_jsons` -> do we need to implement custom logic, or can we just plug them in as additional events?
	- see `create_person_dict.py`; line 147 seems to sort events by days since first? -- so we should be able to just dump together the events from household and from existing files?
- The format of some variables is not standardized
	- for instance, `daySinceFirstEvent` in job_yearly is INT, while it's DOUBLE
	- rinpersoon is in character in the `household` files
	- not all of this may matter, but it creates more work. It may make sense to ask for a standardized output format from Lucas

#### Need to check
- what is `time_key`? -> see config

**Comment by tanzir5** [comment]
@f-hafner We discussed all of the above yesterday. 

- [ ] There is one thing still needed to be done with the household data from Lucas. We need to break it into begin and end events. Please let me know once it is done.
