### ISSUE TITLE
add parquet data loading to deepwalk

### ISSUE THREAD

**Issue by f-hafner** [odissei-lifecourse/life-sequencing-dutch#107]
important is to read only a single row for each node in one epoch.

the following works on dummy data, using duckdb:
```sql
with numbered_rows AS (
  select *, ROW_NUMBER() OVER (PARTITION BY SOURCE ORDER BY SOURCE) as row_id
  from read_parquet('/projects/0/prjs1019/data/graph/walks/layered_walks_2010.parquet')
  )
  select *
  from numbered_rows
  where row_id = 4; # 4 is the epoch id
```

add this functionality here: https://github.com/odissei-lifecourse/life-sequencing-dutch/blob/aaaa0d00c7edaee02653fd51624eef5def07da8e/pop2vec/graph/src/deepwalk_dataset.py#L19

**Comment by f-hafner** [comment]
@dakota0064 , do you see any problems down the line if doing this?

**Comment by dakota0064** [comment]
I don't know a ton about parquet, but I imagine it should be fine. If you can get it into a dataframe that's great, but if not you would just need to change the __len__ and __getitem__ functions to work correctly with whatever data structure it uses.
