### ISSUE TITLE
overflow error when running inference

### ISSUE THREAD

**Issue by f-hafner** [odissei-lifecourse/life-sequencing-dutch#121]
when running `infer_embedding.py`, I get
```python
in .../torch/_tensor.py:1032: RuntimeWarning: overflow encoundered in cast
   return self.numpy().astype(dtype, copy=False)
.../h5py/_hl/base.py:118: RuntimeWarning: overflow encountered in cast
  data = np.asarray(data, order="C", dtype=as_type)
```

the warning is shown only once.

might be related to this: https://github.com/onnx/onnx/issues/5139

I don't have time to fix this right now, so just running inference_v0.1 with this warning.

**Comment by f-hafner** [comment]
this also happens when converting the embeddings from hdf5 to parquet, and prevents me from creating the embedding parquets.

**Comment by tanzir5** [comment]
Are you getting this error while converting embeddings from hdf5 to parquet?

An error occurred: Unhandled type for Arrow to Parquet schema conversion: halffloat

**Comment by f-hafner** [comment]
>Are you getting this error while converting embeddings from hdf5 to parquet?

No, I'm not getting any errors with halffloat. instead, it's the same error as described in the opening post.

**Comment by f-hafner** [comment]
yes you're right, sorry. I *do* get the same warning, and the conversion to parquet runs through very fast, creating an empty parquet file. that's why I inferred that the warning is causing this problem, but I'm not sure

**Comment by f-hafner** [comment]
There was a bug in writing of hdf5 files. it seems to work now, but I noticed another problem: #125
