### ISSUE TITLE
Get Richer data

### ISSUE THREAD

**Issue by tanzir5** [odissei-lifecourse/life-sequencing-dutch#16]
We need to get better data for the language model. This spreadsheet explains what we are utilizing currently: 
https://docs.google.com/spreadsheets/d/1JzdWpDeB5gWeXaw99akgy8virZq7ERiS6WcZKXKNf0k/edit#gid=0

We need to figure out which files from here are not too expensive (Tom question) and maybe good for the LM to train on. https://www.cbs.nl/en-gb/our-services/customised-services-microdata/microdata-conducting-your-own-research/microdata-catalogue

**Comment by f-hafner** [comment]
we have data now; should maybe process them better.
