### ISSUE TITLE
pretrain exits without training and without errors

### ISSUE THREAD

**Issue by f-hafner** [odissei-lifecourse/life-sequencing-dutch#18]
Problem:  run `pretrain.py` with most recent commits
- finishes early without training and without raising error (in stderr file)
- the same happens when using a single GPU

Then, I rolled back to version before my sync commit (ie, old pretrain that worked on a single gpu). Using a single GPU, tThe script does not fail; I left it run for 6 minutes and I suspect it would have gone into training had I let it run for longer. 

Have not been able to try multi-gpu case because the OSSC does not seem to like the `scancel` command.

**Comment by tanzir5** [comment]
The issue only arises when we use DDP over MPI, regardless of the number of gpus. Interestingly it works okay for the dummy model. I should verify on Snellius that the language model can train using DDP over MPI, and also maybe on Stony Brook server once we have fake data.
