### ISSUE TITLE
LLM training fails with MPI

### ISSUE THREAD

**Issue by f-hafner** [odissei-lifecourse/life-sequencing-dutch#23]
when running `pretrain.py` with 1 or 4 GPUs and the DDPStrategy as described in the docs, I get the following error

```bash
"PyTorch/1.12.0-foss-2022a-CUDA-11.7.0/lib/python3.10/.../torch/distributed/utils.py", line 113, in _sync_module_states _sync_params_and_buffers(
"PyTorch/1.12.0-foss-2022a-CUDA-11.7.0/lib/python3.10/.../torch/distributed/utils.py", line 131 in _sync_params_and_buffers
dist._broadcast_coalesced(
IndexError: map::at
srun: error: tasks 0, 2-3: exited with exit code 1
```

This is related to MPI: in `pretrain.py`, we're using the following strategy: 
```python
ddp = DDPStrategy(process_group_backend="mpi")
```

We use the following bash scripts:
https://github.com/odissei-lifecourse/life-sequencing-dutch/blob/main/code/llm/slurm_scripts/pretrain_multigpu.sh
https://github.com/odissei-lifecourse/life-sequencing-dutch/blob/main/code/llm/slurm_scripts/pretrain.sh

**Comment by f-hafner** [comment]
this definitely seems to be an issue with MPI. when we run with 1 GPU and use the default strategy (ie, do not specify to use `strategy=DDPStrategy(process_group_backend="mpi")`, the code works fine.

**Comment by f-hafner** [comment]
Question from SURF: why do we not use the 2023 software stack? It's compiled against a more recent version of MPI and should be better supported.

We can try to move to the 2023 stack. @dakota0064 , @tanzir5 , do you any reason right now why this might not be possible?

**Comment by f-hafner** [comment]
Hi @benczaja , I don't have any publicly available data at the moment, but am working on it. I'll let you know when they are ready 1.5-2 weeks from now). see #40

**Comment by f-hafner** [comment]
Hi @benczaja , I have the data ready now on snellius, but currently a dependency problem: #32 . I'll keep you posted.

**Comment by f-hafner** [comment]
@benczaja , the data are now ready, and the code on the branch `llm-pipeline-snellius` works as follows.
I want to merge the branch soon, but it requires some tidying. In the meantime, feel free to work with the code on the branch. The following should work

```bash
git clone git@github.com:odissei-lifecourse/life-sequencing-dutch.git
cd life-sequencing-dutch
module purge
module load 2022
module load Python/3.10.4-GCCcore-11.3.0
module load SciPy-bundle/2022.05-foss-2022a
module load h5py/3.7.0-foss-2022a
module load matplotlib/3.5.2-foss-2022a
python -m venv .venv 
source .venv/bin/activate 
pip install -r requirements/snellius.txt
pip install performer-pytorch==1.1.4
```

and then you can run the code either with
```bash
cd life-sequencing-dutch/src/llm
sbatch slurm_scripts/pretrain.sh
```

or within an interactive job
```bash
cd life-sequencing-dutch/src/llm
source slurm_scripts/pretrain.sh
python -m src.new_code.pretrain.sh projects/dutch_real/pretrain_cfg.json

```

In `src/llm/new_code/pretrain.py` you see some constants at the top of the script that you can adjust for how training should be done. I've not had time to try all options out, so there may be bugs.

I tried to use MPI, but I got `RuntimeError: Distributed package doesn't have MPI built in. MPI is only included if you build PyTorch from source on a host that has MPI installed.`, the reason for which is I think that we use pytorch from pip and not from modules.

Let me know if you have questions.

**Comment by benczaja** [comment]
Hey we need to either build PyTorch from source or use our system Pytorch (which was built from source). Because pip will not install PyTorch with MPI functionality.... Or at least I don't know how to instruct pip to do so. 
https://discuss.pytorch.org/t/distributed-package-doesnt-have-mpi-built-in/196094

**Comment by benczaja** [comment]
OK it looks as though certain communication routines are not implemented in the DDP strategy MPI
 - https://pytorch.org/docs/2.4/distributed.html#backends (see the question marks)
 - The `dist._broadcast_coalesced` error reported above I think falls into this. So its how PyTorch lightning has implemented the collective communication calls of PyTorch. MPI is just lacking (my guess). They seem to give more support to NCCL and gloo https://pytorch.org/docs/2.4/distributed.html#which-backend-to-use . They simply mention MPI no-where.

So the solution for now is just use `gloo` as the ddp strategy.
- I have re-written pretrain.py a bit to easily take in arguments https://github.com/odissei-lifecourse/life-sequencing-dutch/blob/4d10b2da9989959d8adbcfbc103773718dc6b36a/src/llm/src/new_code/pretrain.py#L144
- It can now be used like this https://github.com/odissei-lifecourse/life-sequencing-dutch/blob/4d10b2da9989959d8adbcfbc103773718dc6b36a/src/llm/slurm_scripts/pretrain_multigpu_singlenode.sh#L23

- Have done some simple bench-marking seeing the difference between gloo vs NCCL. NCCL reports ~ `3.51 iterations/s` and gloo `3.3 iterations/s` this is not a glaring difference, and somehting I think we can live with in the OSSC
- The biggest performance increase would just be using more of the GPUs. The GPUs are simply under- utilized. I see about the usage of about 30% of the GPUs when running. But I assume that this is just model and data dependant. So when the model size is increased and/or the data is increased then we will really use the GPUs. THEN NCCL will probably be more of an issue.

**Comment by benczaja** [comment]
GPU utilization for context 
![Screenshot 2024-07-30 at 14 41 42](https://github.com/user-attachments/assets/273afb5f-72d6-4605-aaf7-977ba82f93de)

**Comment by f-hafner** [comment]
I reproduced this for `ddpstrategy` in (gloo, auto, ddp). I get 1.65 it/s with gloo and 1.75 with the other two, and around 30% GPU usage.

**Comment by f-hafner** [comment]
> I see about the usage of about 30% of the GPUs when running. But I assume that this is just model and data dependant. So when the model size is increased and/or the data is increased then we will really use the GPUs. THEN NCCL will probably be more of an issue.

What I'll do next is increase the utilization of the GPUs used. This means bigger batch size, more parameters and/or higher precision. Increasing the size of individual samples would be an option too, but that's not straightforward to do at the moment.

**Comment by f-hafner** [comment]
I realize we forgot to use srun. So, my plan is now
- https://lightning.ai/docs/pytorch/stable/clouds/cluster_advanced.html -- use srun! then compare differences again
- make a table comparing
	- model size/batch size
	- backend used
- then, check also
	- GPU utilization (tensor cores)
	- do we get a speedup with multiple GPUs?
- depending on that, discuss with Tanzir on the next steps

**Comment by f-hafner** [comment]
Here are some comparisons from using `srun python -m ...`

|            |        | auto      |    auto             | gloo      |       gloo          |
|------------|--------|-----------|-----------------|-----------|-----------------|
| model size | N gpus | speed     | gpu utilization | speed     | gpu utilization |
| small      | 4      | 2.94 it/s | 15.00%          | 2.97 it/s | 10.00%          |
| large      | 4      | 2.00it/s  | 30-50%          | 1.92 it/s | 30-50%          |
| large      | 2      | 2.01 it/s | 40.00%          | 1.95 it/s | 30.00%          |

(note, using srun makes the code faster, but not differentially so between nccl and gloo backends)

- the gpu utilization is always fluctuating a log (see Ben's figure above), which suggests that either there is a bottleneck in data loading, or there are other inefficiencies. for data loading bottleneck, I need to check if we're CPU-constrained: https://github.com/Lightning-AI/pytorch-lightning/issues/18650. I have quickly tried what is discussed there but found no difference.
- For other inefficiencies, my colleagues suggested to profile the code with [Nsight](https://developer.nvidia.com/nsight-systems/get-started)
-  mixed precision/tensor core utilization still not investigated.
- the lack of speedup between 2 and 4 gpus is puzzling

**Comment by f-hafner** [comment]
The conclusion from here is to not use MPI. I'm closing this in favor of #74 .
