### ISSUE TITLE
Next export

### ISSUE THREAD

**Issue by f-hafner** [odissei-lifecourse/life-sequencing-dutch#4]
### To include
- new reports 
- summary statistics for fake data
   - which are the relevant files
   - statistics for numeric variables: mean, sd, N missing, min, max, covariance matrix
   - frequency of each category for all categorical variables 
- codes that are not yet on github
   - Lucas' scripts 
   - Code from Dakota

**Comment by f-hafner** [comment]
@Lsage , I created a private fork of the repo we discussed today: https://github.com/odissei-lifecourse/cbs_validationdata

Have a look; if it's too much work to create fake data also for all original files, we can focus on the intermediate ones.

**Comment by tanzir5** [comment]
@f-hafner This looks very interesting. Can we generate synthetic version of all CBS files on our local computer using these scripts without access to actual CBS data? If not, can you tell me what these can do?

**Comment by Lsage** [comment]
Done @f-hafner

**Comment by f-hafner** [comment]
Update: current export was not approved

To be fixed
- which variables, besides the ones in the document, are restricted? 
- make it runnable on the `work_env`? -> sample for all files, but count total number of records in the file
- drop numeric identifying variables from the covariance matrix
- use different file format for export. for instance an excel workbook with different tabs: one tab for covariance matrix, one tab for the per-variable summary statistics

**Comment by f-hafner** [comment]
we don't have code for running the network stats on work env, and it's not a priority at the moment. closing.
