### ISSUE TITLE
database for socio-economic data

### ISSUE THREAD

**Issue by f-hafner** [odissei-lifecourse/life-sequencing-dutch#61]
make a sqlite database with roughly the following schema
- one table with person characteristics that are fixed over time, ie gender, birth year, municipality of birth, ....
  ```sql
   create table person_background as [...]
   create unique index idx_pb_person on person_background(rinpersoonid)
   ```
   - feel free to use a better/shorter column name for rinpersoonid
- one table with annual data, ie income. unique index on `(rinperson, year)`
- a table with marriages. I think it should have `rinpersoon1`, `rinpersoon2`, and background info on the marriage, ie marriage date/year/place. index on `(rinperson1, rinperson2)`.

use following convention for index names: `idx_a_b`, where `a` is an abbrevation of the table name on which the index is created, and `b` indicates which columns constitute the index

**Comment by f-hafner** [comment]
@dakota0064 , https://github.com/odissei-lifecourse/life-sequencing-dutch/commit/f75afd657ea6e0edefae2768131d591592d3103e creates a separate db for each table, is that correct? I thought we could have all tables in the same single sqlite database? or is there a reason to keep them in separate files?

**Comment by dakota0064** [comment]
In my past work I kept tables as separate files because the data was structured in a way that was convenient. But there's no benefit to doing that here, so I will combine them all together.

**Comment by dakota0064** [comment]
Going to close this as we now have the background info in one database.
