### ISSUE TITLE
Where does the background data (like gender, birth_municipality, birth_year) come from?

### ISSUE THREAD

**Issue by tanzir5** [odissei-lifecourse/life-sequencing-dutch#89]
The data exists in /home/data/llm/raw/background.csv on OSSC under our project.

But what is the source of this?

**Comment by tanzir5** [comment]
Lucas provided all CBS documentation with English translation and it's uploaded here: 

https://github.com/odissei-lifecourse/life-sequencing-dutch/blob/main/docs/Micro%20data%20description.zip

**Comment by f-hafner** [comment]
to ease CBS review, I moved all non-code things, including the above files, into https://github.com/odissei-lifecourse/data
